[package]
name = "equity"
version.workspace = true
edition.workspace = true

[features]
default = ["cxx-bridge"]
cxx-bridge = []

[dependencies]
serde.workspace = true
anyhow.workspace = true
crypto = { path = "../crypto" }
utility = { path = "../utility" }
cxx = "1.0"
hex = "0.4"
bs58 = { version = "0.5", features = ["check"] }
sha2 = "0.10"

[build-dependencies]
cxx-build = "1.0"
